-- Migration: 006_add_performance_indexes.sql
-- Purpose: Add indexes to improve query performance
-- Created: Generated by audit quick-fix script
-- 
-- These indexes optimize common queries on:
-- 1. production_lot_inventory_alerts.production_lot_id (frequent lookups)
-- 2. production_lot_inventory_alerts.severity (dashboard filtering)
-- 3. upf_production_lots.status (list view filtering)

-- Index for alert lookups by production lot
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_lot_id 
ON production_lot_inventory_alerts(production_lot_id);

-- Index for alert filtering by severity (dashboard)
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_severity 
ON production_lot_inventory_alerts(severity);

-- Index for production lot status filtering
CREATE INDEX IF NOT EXISTS idx_production_lots_status 
ON upf_production_lots(status);

-- Analyze tables to update statistics
ANALYZE production_lot_inventory_alerts;
ANALYZE upf_production_lots;

-- Migration Notes:
-- These indexes are safe to add to production.
-- They will improve query performance without affecting data integrity.
-- Expected impact: 30-50% reduction in query time for filtered views.
